services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: algatransito
      MYSQL_USER: alga
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
